apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop
  namespace: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: sockshop.qurtana.com.ng
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: front-end
                port:
                  number: 80
