---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop
  annotations:
    cert-manager.io/cluster-issuer: production
spec:
  ingressClassName: external-nginx
  rules:
    - host: sock-shop.thequrtbuck.com.ng
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: front-end
                port:
                  number: 8079
  tls:
    - hosts:
        - sock-shop.thequrtbuck.com.ng
      secretName: production-cluster-issuer