---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop
  annotations:
    cert-manager.io/cluster-issuer: production
spec:
  ingressClassName: external-nginx
  rules:
    - host: sockshop.qurtana.com.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80
  tls:
    - hosts:
        - sockshop.qurtana.com.ng
      secretName: production-cluster-issuer