name: Deploy Sockshop on AKS

on:
  workflow_dispatch:
    inputs:
      action:
        description: Action to perform
        required: true
        default: build
        type: choice
        options:
          - build
          - cleanup

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        uses: pietrobolcato/install-azure-cli-action@v1.0.1

      - name: Install necessary tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip wget apt-transport-https gnupg2 software-properties-common git ca-certificates

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.7.5

      - name: Install kubectl
        run: |
          sudo snap install kubectl --classic

      - name: Install Helm
        uses: Azure/setup-helm@v4
        with:
          version: v3.7.0
          token: ${{ github.token }}
          downloadBaseURL: https://get.helm.sh
          

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform setup and apply/destroy (infrastructure)
        run: |
          cd infrastructure && \
          terraform init || { echo "Terraform initialization failed"; exit 1; } && \
          terraform validate || { echo "Terraform validation failed"; exit 1; } && \
          if [ "${{ github.event.inputs.action }}" = "build" ]; then
            terraform plan -out=tfplan || { echo "Terraform planning failed"; exit 1; } && \
            terraform apply tfplan || { echo "Terraform apply failed"; exit 1; }
          elif [ "${{ github.event.inputs.action }}" = "cleanup" ]; then
            terraform destroy -auto-approve || { echo "Terraform destroy failed"; exit 1; }
          fi

      - name: Wait for k8s cluster to be ready
        run: sleep 60

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group capstonerg --name capstoneaks

      - name: Terraform setup and apply/destroy (helm_charts)
        run: |
          cd helm_charts && \
          terraform init || { echo "Terraform initialization failed"; exit 1; } && \
          terraform validate || { echo "Terraform validation failed"; exit 1; } && \
          if [ "${{ github.event.inputs.action }}" = "build" ]; then
            terraform plan -out=tfplan || { echo "Terraform planning failed"; exit 1; } && \
            terraform apply tfplan || { echo "Terraform apply failed"; exit 1; }
          elif [ "${{ github.event.inputs.action }}" = "cleanup" ]; then
            terraform destroy -auto-approve || { echo "Terraform destroy failed"; exit 1; }
          fi

      - name: Extract subscriptionId
        id: extract_sub
        run: echo "::set-output name=subscription_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')"
        shell: bash

      - name: Get AKS credentials
        id: get_credentials
        uses: azure/aks-set-context@v1
        with:
            subscriptionId: ${{ steps.extract_sub.outputs.subscription_id }}
            resource-group: capstonerg
            cluster-name: capstoneaks

      - name: Apply microservices YAML
        run: |
          cd microservices && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply microservices YAML after 2 attempts"
              exit 1
            fi
            echo "Retrying applying microservices YAML (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Apply letsencrypt YAML
        run: |
          cd letsencrypt && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply letsencrypt YAML after 2 attempts"
              exit 1
            fi
            echo "Retrying applying letsencrypt YAML (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Apply argocd YAML
        run: |
          cd argocd && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply argocd YAML after 2 attempts"
              exit 1
            fi
            echo "Retrying applying argocd YAML (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Apply nginx-ingress YAML
        run: |
          cd ingress && \
          attempt=1 && \
          until kubectl apply -f nginx-ingress.yml; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply nginx-ingress YAML after 2 attempts"
              exit 1
            fi
            echo "Retrying applying nginx-ingress YAML (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Wait for nginx-ingress to be ready
        run: sleep 30

      - name: Apply sock-shop YAML in ingress directory
        run: |
          cd ingress && \
          attempt=1 && \
          until kubectl apply -f sock-shop.yml; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply sock-shop YAML in ingress directory after 2 attempts"
              exit 1
            fi
            echo "Retrying applying sock-shop YAML in ingress directory (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Wait for 10 seconds before applying Prometheus Stack YAMLs
        run: sleep 10

      - name: Apply Prometheus Stack CRDs
        run: |
          cd prometheus_stack/crds && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply Prometheus Stack CRDs after 2 attempts"
              exit 1
            fi
            echo "Retrying applying Prometheus Stack CRDs (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Wait for 10 seconds before applying Prometheus Operator YAMLs
        run: sleep 10

      - name: Apply Prometheus Operator YAML
        run: |
          cd prometheus_stack/prometheus-operator && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply Prometheus Operator YAML after 2 attempts"
              exit 1
            fi
            echo "Retrying applying Prometheus Operator YAML (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Wait for 10 seconds before applying Prometheus YAMLs
        run: sleep 10

      - name: Apply Prometheus YAML
        run: |
          cd prometheus_stack/prometheus && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply Prometheus YAML after 2 attempts"
              exit 1
            fi
            echo "Retrying applying Prometheus YAML (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Wait for 10 seconds before applying Grafana YAMLs
        run: sleep 10

      - name: Apply Grafana YAML
        run: |
          cd prometheus_stack/grafana && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply Grafana YAML after 2 attempts"
              exit 1
            fi
            echo "Retrying applying Grafana YAML (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Wait for 10 seconds before applying Alert Manager YAMLs
        run: sleep 10

      - name: Apply Alert Manager YAML
        run: |
          cd prometheus_stack/alertmanager && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply Alert Manager YAML after 2 attempts"
              exit 1
            fi
            echo "Retrying applying Alert Manager YAML (attempt $attempt)"
            sleep 10
            ((attempt++))
          done

      - name: Wait for 10 seconds before applying ELK Stack YAMLs
        run: sleep 10

      - name: Apply namespace.yaml in elk_stack directory
        run: |
          cd elk_stack && \
          kubectl apply -f namespace.yaml || kubectl apply -f namespace.yaml

      - name: Apply other YAML files in elk_stack directory
        run: |
          cd elk_stack && \
          attempt=1 && \
          until kubectl apply -f .; do
            if [ $attempt -eq 2 ]; then
              echo "Failed to apply YAML files in elk_stack directory after 2 attempts"
              exit 1
            fi
            echo "Retrying applying YAML files in elk_stack directory (attempt $attempt)"
            sleep 10
            ((attempt++))
          done
